server:
  port: 9081
  servlet:
    context-path: /consumer
spring:
  rabbitmq:
    host: 192.168.247.130
    port: 5672
    username: admin
    password: admin
    #消费者 消息确认机制 自动确认
    listener:
      simple:
        acknowledge-mode: manual
