server:
  port: 9080
  servlet:
    context-path: /productor
spring:
  rabbitmq:
    host: 192.168.247.130
    port: 5672
    username: admin
    password: admin

    #消息确认配置项
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true
